name: dancer_ranking_app
description: A social dancer's companion app for planning and tracking dance events

publish_to: 'none'

version: 2.2.0+220

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Core dependencies for building the app
  provider: ^6.0.5
  intl: ^0.19.0
  uuid: ^4.0.0
  
  # Database / Persistence
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # File handling for imports
  file_picker: ^8.0.0
  desktop_drop: ^0.4.4

  # UI & Date/Time
  flutter_datetime_picker: ^1.5.1

  # Native toasts
  fluttertoast: ^8.2.4

  # App information
  package_info_plus: ^8.0.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build runner for code generation
  drift_dev: ^2.20.1
  build_runner: ^2.4.13

  # Linting
  flutter_lints: ^3.0.0

  # App customization
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# App Icon Configuration
flutter_launcher_icons:
  android: true
  macos: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
